### ISSUE TITLE
Question: What does the autoResize mean?

### ISSUE THREAD

**Issue by necramirez** [koola/pix-diff#39]
Based on https://github.com/koola/pix-diff/blob/6ebf6521e7b2d98f336fafc28c3801ec628b3482/index.js#L83-L85

```
        else if (this.autoResize) {
            browser.driver.manage().window().setSize(this.width, this.height);
        }
```

`autoResize` will force-resize the browser to the provided `width` and `height` parameters. Is that correct? Is that all?

**Comment by wswebcreation** [comment]
The previous version of PixDiff set the height and the width of the window based on the parameters that were given in the `onPrepare` of Protractor.
Last version we made this configurable because it is not always needed / wanted. Each testcase can have a different set of screensizes. 
Providing `autoResize : false` should not resize the screen to the default / provided width and height.
Hope this is more clear now

**Comment by necramirez** [comment]
👍 This is relevant to the next issue I'm writing. 😛
