### ISSUE TITLE
remove assert on browserName

### ISSUE THREAD

**Issue by josephlaw** [koola/pix-diff#43]
i prefer remove below statement in pix-diff's index.js, when testing with native mobile application.
`        assert.ok(_.capabilities.browserName, 'Browser name is undefined.');`

**Comment by wswebcreation** [comment]
The tool is initially not build to test apps on mobile
What kind off app do you have, a native or a hybrid app?
What are the capabilities you at least use to test your app?

**Comment by josephlaw** [comment]
hi @wswebcreation, my app is built in hybrid and native, and run testing using Appium. if I set a value in browserName then the Appium will trigger the browser in the mobile device.

**Comment by wswebcreation** [comment]
Just curious about the native part, does the app start with the native part and if so, how do you automate this with Protractor because it normally fails when starting a native app without a webview in the first screen.

To get back at your capabilities. What is the bare minimum capability that you need to provide to appium to open your app? 
If there is one, can we then say that if no browserName is provided, the app capability needs to be there. And if it is also not there, then the process should fail

**Comment by josephlaw** [comment]
sorry for my typo that I only develop in hybrid.  You are right that I set browserName='', the app capability needs to be there. And if it is also not there, then the process should fail.

**Comment by wswebcreation** [comment]
But still, what is the capability that you need to start your app?

Is that 'app' ?

**Comment by josephlaw** [comment]
@wswebcreation, i use capabilities as below for your reference, thanks
```
multiCapabilities: [{
       platformName: 'Android',
       platformVersion: '7.0',
       deviceName: 'Android Emulator',
       browserName: '',
       autoWebview: true,
       platform: 'Android',
       app: './android-debug.apk',
       automationName: 'Appium',
       nativeWebScreenshot: true,
     }
```

**Comment by koola** [comment]
Hi @josephlaw, planning on adding Appium support very soon, see [feat/appium](https://github.com/koola/pix-diff/tree/feat/appium)

**Comment by wswebcreation** [comment]
@koola

Can you check hangouts?
